version: 2.1
description: Orb for Etsy gallery component clone project

jobs:
  test:
    docker:
      - image: circleci/node
      - image: circleci/mysql
        environment: 
          MYSQL_USER: student
          MYSQL_PASSWORD: student
          MYSQL_DATABASE: gallery
    steps:
      - checkout
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run: 
          name: Install MySQL, start server, install dependencies, seedDB and run tests
          command: |
            sudo apt-get install default-mysql-client
            npm install
            npm run reset-db
            npm run test
      

